### PR TITLE
More Engineer review data

### PR DESCRIPTION
**Pull request by medamer**

### CODE REVIEW

**Review by trevorwjames — APPROVED** [review]
It looks like this is the merged updated data. It is not loading the diff, did you engineer any features on top of that?

**Comment by medamer** [comment]
Like we discussed earlier, I added "Yes" to the column "Engineer review" to the world dataset

**Comment by trevorwjames** [comment]
Are you also planning on continuing to create the "good site" column as well, to establish a target for modeling?

**Comment by medamer** [comment]
Yes I have this dataset loaded to the Notebook and I created the column "good site"

**Pull request merged**
